server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ssns
    username: ssns
    password: ssns
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: com/aic/ssns/**/mapper/*.xml